char: random: upsteam to 1.40.1 Squashed commit of the following:
commit 1bfe7c329f31115a185e473373b04544068636c4
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:46:34 2022 +0800

    char: srandom: disable logging

    ref: 2c46f17e31cba28936081430e52b8a736432fea1

commit 1891243c27d5f15ced30257b649c32945715c094
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:34:36 2022 +0800

    char: srandom: remove srandom stack guard

commit 810cdbba141895823bd46f6efa9a99ff58d6c308
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 12:33:55 2022 +0800

    char: random: fix unused function error

    ../drivers/char/random.c:1036:16: error: unused function 'extract_crng_user' [-Werror,-Wunused-function]
    static ssize_t extract_crng_user(void __user *buf, size_t nbytes)
                   ^
    1 error generated.

commit 3ad62049fb7a9795d6bda612825b50d3ca8cb855
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 17:28:36 2020 +0530

    char: mem: register /dev/hw_random through devmem framework when HW_RANDOM is unset

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit a7a162d40541b2528198dd280b39c9401d2444ca
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 16:52:42 2020 +0530

    char: srandom: switch to kzalloc

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit c091714fc39d7d4961c50f91e8796b29f5bfa6b5
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed Dec 16 03:14:44 2020 +0530

    char: srandom: change TIMESPEC struct variable to tsp

    some focaltech touchscreens also export symbols with ts variable causing linker errors

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit b931db6091e4e4b398d666b6b45576ed8adc0079
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Wed May 19 06:22:10 2021 +0530

    char: random: use sdevice_{read,write} for {u}random fops

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/random.c

commit 63e19b0db662ea4db0a610893691489aa3e1fd11
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 20:03:42 2020 +0530

    char: mem: link /dev/{u}random to /dev/srandom

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit c5bde6607ded38a481c444adaa6980a5b6a3f5db
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 20:02:31 2020 +0530

    char: srandom: expose sdevice_{read,write} and sfops for treewide usage

    * de-staticify, externify and move the prototypes to srandom.h
    * constify sfops
    * also export sdevice_read and sdevice_write as symbols

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

     Conflicts:
    	drivers/char/srandom/srandom.c

commit bf674ea191ee352da16f03ff614c5febdb712075
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 18:03:09 2020 +0530

    char: srandom: use ktime_get_real_ts64 and timespec64

    * these were introduced in v3.17-rc1, so let's use them

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit acc6a55acf9d15cb7fc12b7d77b55cd7b88d1155
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Tue Dec 15 17:42:52 2020 +0530

    char: srandom: expose new Makefile and Kconfig interfaces

    * deprecated the original Makefile
    * added Kconfig interfaces for selecting CONFIG_SRANDOM

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 5a4080c8f41553281531702041debd5b500c319f
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Mon Nov 15 21:21:48 2021 +0530

    char: srandom: add Kconfig interface

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit b048e071eaaa0499aa90e25fae8648eec1f5606a
Author: Jebaitedneko <Jebaitedneko@gmail.com>
Date:   Mon Nov 15 21:19:15 2021 +0530

    char: srandom: rewite Makefile for in-kernel builds

    Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

commit 09f5511a186bb4dd1ee660c1d9cd422ed66bd006
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Sat Mar 12 01:12:49 2022 +0800

    drivers: Checkout drivers/char/srandom from https://github.com/josenk/srandom/commits/master

commit ea50fcc185edfaa385f676b5ff99cda799aa711b
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:29 2022 +0800

    Revert "drivers: char: Add snapshot of srandom from josenk/srandom"

    This reverts commit b4aeb07fbe32896cc3b28a8e91e8ac9c5c528eca.

commit 240e7b83f738e391b45cb7d64ce19cc515f8e95a
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:29 2022 +0800

    Revert "char: srandom: Refactor for sanity and consistency"

    This reverts commit b64391ad945bd5b4fd7a42a85bd7db4d08ae7d18.

commit 1333600c3665a3aba2527513cee0e4cc2cc23225
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:28 2022 +0800

    Revert "char: srandom: Avoid printk logging in srandom"

    This reverts commit f2a62bbd8f37c662c74201de16c9ea857f1608d2.

commit a9e795e1ea847a603fad593cf281aabaa31a0730
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:27 2022 +0800

    Revert "char: srandom: Fix comparison ordering warning"

    This reverts commit 78f16207586f64b52fd8dbeadbc31868f0a49385.

commit b4b574c65a0ebcfdf9ad93916a4b799ed624b8be
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:26 2022 +0800

    Revert "char: srandom: use ktime_get_real_ts64 and timespec64"

    This reverts commit 6236bb98c39fd637f47b4017899e10f4755ae250.

commit c9d0ed85ff2946617cf7438f5f3d691064b62d45
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:26 2022 +0800

    Revert "char: srandom: switch to kzalloc"

    This reverts commit 4ec60afc4ddb24e11a847ae7479dd351c121435e.

commit 809bf4b6ee414159c4e9c1ec97686515625195dd
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:25 2022 +0800

    Revert "char: srandom: Expose sdevice_{read,write} and sfops for external usage"

    This reverts commit 0552652713f8c0afcfeb174888abe74ee40905bf.

commit 247389fc37bec0b88abd813915b66c56ae5c4ca7
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:55:24 2022 +0800

    Revert "char: mem: link /dev/{u}random to /dev/srandom"

    This reverts commit 6f5140215d05789443fa119959f79b1733131cc5.

commit a05a0d4596ec32a9902b11039a0f205693459427
Author: pwnrazr <1644943+pwnrazr@users.noreply.github.com>
Date:   Fri Mar 11 23:54:56 2022 +0800

    Revert "char: srandom: Silence logging"

    This reverts commit ccc0e43aa5616031eb50df2b078b115f2b122895.